### ISSUE TITLE
Editing .config file

### ISSUE THREAD

**Issue by tbazilegith** [UPHL-BioNGS/Donut_Falls#4]
Hi Erin,
I edited the UPHL.config file calling it FBPHL.config
Within the file, I edited the comment portion, replacing it with the path of  my Donut_Falls.nf file:
nextflow run /home/bi_fellow/Donut_Falls/Donut_Falls.nf -c /home/bi_fellow/Donut_Falls/configs/FBPHL.config -with-dag donut_falls_$(date +"%y-%m-%d-%H%M%S").png
Was that right?
However, when I run this
 nextflow run UPHL-BioNGS/Donut_falls -profile singularity --reads LR_fastqs/barcode01.fastq.gz --reads reads
I got this
`UPHL-BioNGS/Donut_falls` currently is sticked on revision: erin-dev -- you need to specify explicitly a revision with the option `-r` to use it
What could be the issue?
Thanks,
TJ

**Comment by erinyoung** [comment]
The issue is that I need to update my documentation. 

You probably want something more to the effect of

```
nextflow run UPHL-BioNGS/Donut_falls -profile singularity -r main --reads LR_fastqs
```

**Comment by erinyoung** [comment]
I am going to warn you, though, polca polishing with illumina reads requires masurca and polca to be in the path.

**Comment by tbazilegith** [comment]
Thanks!
Also, when I run this 
nextflow run Donut_Falls.nf -c configs/singularity.config
I got this error message:
Could not find 'fastq_pass' directories. Set with 'params.fastq_pass_directory'
_regardless I am in the fastq_pass directory of its parent dir.
- What does params.fastq_pass_directory mean?
- It is like an option to add to the commands (--params.fastq_pass_directory) and having after fastq_pass dir? I tried that, but got the same error: 
Could not find 'fastq_pass' directories. Set with 'params.fastq_pass_directory'
Thanks!
TJ

**Comment by tbazilegith** [comment]
Sorry,
nextflow run UPHL-BioNGS/Donut_falls -profile singularity -r main --reads LR_fastqs
triggered:
Missing project main script: /home/myusername/.nextflow/assets/UPHL-BioNGS/Donut_falls/main.nf
Thanks!
TJ

**Comment by erinyoung** [comment]
> Thanks! Also, when I run this nextflow run Donut_Falls.nf -c configs/singularity.config I got this error message: Could not find 'fastq_pass' directories. Set with 'params.fastq_pass_directory' _regardless I am in the fastq_pass directory of its parent dir.
> 
> * What does params.fastq_pass_directory mean?
> * It is like an option to add to the commands (--params.fastq_pass_directory) and having after fastq_pass dir? I tried that, but got the same error:
>   Could not find 'fastq_pass' directories. Set with 'params.fastq_pass_directory'
>   Thanks!
>   TJ

It means that I forgot to remove an old workflow. That should be resolved now.

**Comment by erinyoung** [comment]
> Sorry,
> nextflow run UPHL-BioNGS/Donut_falls -profile singularity -r main --reads LR_fastqs
> triggered:
> Missing project main script: /home/myusername/.nextflow/assets/UPHL-BioNGS/Donut_falls/main.nf
> Thanks!
> TJ

As for this issue, it also my fault. 100%. 'Donut_Falls' has two capitals, not one. The command I sent earlier had a typo.

It should be 
```
nextflow run UPHL-BioNGS/Donut_Falls --reads combined --out test -r main -profile singularity -c <custom config file>
```

**Comment by erinyoung** [comment]
Thank you again. I've also updated the readme to remove the lowercase typo.

**Comment by tbazilegith** [comment]
Hi Erin,
I did this
nextflow run UPHL-BioNGS/Donut_Falls --reads LR_fastqs/barcode01.fastq.gz --out dunotFalls_test -r main -profile sigularity -c mypath/bi_fellow/Donut_Falls/configs/FBPHL.config
Got this again
Could not find sequencing summary file! Set with 'params.sequencing_summary'
Could not find fastq files for nanopore sequencing. Set with 'params.reads
Best,
TJ

**Comment by tbazilegith** [comment]
Good morning Erin,
My LR_fastqs directory only contains the fastq.gz files, which I copied there. Do I have to add the sequencing summary file into that folder?
Thanks,
TJ

**Comment by erinyoung** [comment]
It's fine that your directory only has one fastq.gz file in it.

The sequencing summery should be optional. The workflow looks in your launch directory for it, but you can specify where it is.

**Comment by tbazilegith** [comment]
Hi Erin,
I got this
Could not find sequencing summary file! Set with 'params.sequencing_summary'
Fastq file found : barcode02
Fastq file found : barcode12
Fastq file found : barcode03
Error executing process > 'nanoplot (nanoplot)'

Caused by:
  Path value cannot be null

Which option do I have to add to  the command to refer to the sequencing summary file?
Thanks!
TB

**Comment by erinyoung** [comment]
You should be able to set `--nanoplot 'false'` with your command to turn off that process.

```
nextflow run UPHL-BioNGS/Donut_Falls --reads LR_fastqs --out dunotFalls_test -r main -profile --nanoplot false
```

**Comment by tbazilegith** [comment]
Hi Erin,
I run this
nextflow run UPHL-BioNGS/Donut_Falls --reads LR_fastqs --out dunotFalls_test -r main -profile singularity --nanoplot false
It produced this (note all my fastq files are found )
Maximum number of CPUS used in this workflow : 32
Could not find sequencing summary file! Set with 'params.sequencing_summary'
Fastq file found : barcode02
Fastq file found : barcode12
Fastq file found : barcode03
Fastq file found : barcode04
Fastq file found : barcode01
Fastq file found : barcode10
Fastq file found : barcode11
Fastq file found : barcode05
Fastq file found : barcode09
Fastq file found : barcode08
Fastq file found : barcode06
[-        ] process > nanoplot -
[-        ] process > fastp    -
[-        ] process > nanoplot -
[-        ] process > fastp    -
[-        ] process > filtlong -
[-        ] process > bgzip    -
[-        ] process > flye     -
[-        ] process > medaka   -
[-        ] process > polca    -
Error executing process > 'nanoplot (nanoplot)'

Caused by:
  Path value cannot be null
Kindly,
TJ

**Comment by erinyoung** [comment]
Do you have a sequencing summery file to point params.sequencing_summary to? 

And perhaps false needs to be 'false'. Hmmm...

**Comment by tbazilegith** [comment]
I have that file in the LR_fastqs directory. I have tried without false, but same thing.

**Comment by erinyoung** [comment]
Now it's giving an error because there's no short reads - which it should be okay with. This is my fault. I should have a fix by the end of today.

**Comment by erinyoung** [comment]
@tbazilegith , my apologies for taking so long, but this workflow _should_ now work without a summary file and without paired-end illumina fastq files

**Comment by erinyoung** [comment]
Also, right now if flye cannot assemble your reads, it throws an error and brings the whole workflow to an abrupt end. If you have fastq files that don't assemble, it's best to move them out of the directory that you're feeding into the workflow.

**Comment by tbazilegith** [comment]
> Also, right now if flye cannot assemble your reads, it throws an error and brings the whole workflow to an abrupt end. If you have fastq files that don't assemble, it's best to move them out of the directory that you're feeding into the workflow.

**Comment by tbazilegith** [comment]
- Hi Erin,
- Does that mean the workflow must be run in the same directory as the fastq files? Note my .fastq.gz are single ends from minION.
- Thanks!

**Comment by erinyoung** [comment]
No, the workflow does not need to be in the same directory as the fastq files.

It does mean that all the fastq files in your directory (which I think is `LR_fastqs`) need to be intended for the workflow. If there are fastq files that you don't want to go through the workflow, they can't be in that directory.

**Comment by tbazilegith** [comment]
Thanks!
