### ISSUE TITLE
Hybrid Assembly Issue

### ISSUE THREAD

**Issue by whottel** [UPHL-BioNGS/Donut_Falls#78]
Hello,

I am trying to run Donut Falls with the Unicycler assembler for some ONT and Illumina reads. 
I am using the following run command:
`/Shared/SHL-BUG/software/nextflow/nextflow run UPHL-BioNGS/Donut_Falls -r main -profile singularity --sample_sheet Sample_Sheet_hybrid.csv --assembler unicycler -c /Shared/SHL-BUG/singularity/Donut_Falls/Donut_Falls_custom.config`
I have tried a couple of different combinations of naming the files, including providing the full path in the sample sheet, but was unable to get it to work.
Only sample 3 appears to run through Unicycler although it looks like the Illumina reads are not being used as input looking at the total Illumina reads column of the pipeline summary. Whereas 1 and 2 seem to be skipped entirely by Unicycler and no assembly output is generated. 
[DF_Hybrid.zip](https://github.com/user-attachments/files/16073269/DF_Hybrid.zip)

I can also provide the ONT and Illumina .fastq files via ShareDrive if needed.

**Comment by erinyoung** [comment]
Awesome....

My lab had an issue with sample swaps with long read sequencing, so there is a mash dist step beforehand. If samples are too distant, the short reads get filtered out.

It looks like, however, that your samples aren't even going to mash dist... but then one sample still goes through unicycler. 

```
name	number_of_reads	mean_read_length	mean_qual	total_illumina_reads	nanopore_illumina_mash_distance	assemblers	unicycler_total_length	unicycler_num_contigs	unicycler_circ_contigs	unicycler_coverage	unicycler_unmapped_nanopore	unicycler_unmapped_nanopore_pc	unicycler_unmapped_illumina	unicycler_unmapped_illumina_pc	unicycler_busco
1	37687	4207.2	10.4	0	NF	unicycler	0	0	0	0	0	0	0	0	NF
2	57191	5098.5	11.7	0	NF	unicycler	0	0	0	0	0	0	0	0	NF
3	69416	4652.4	11.3	0	NF	unicycler	2746128	2	2	114.55	18308	26.37	3329	0	C:100.0%[S:100.0%,D:0.0%],F:0.0%,M:0.0%,n:124
```

Could you share the donut_falls_summary.json file?

**Comment by whottel** [comment]
Sure thing
[donut_falls_summary.json](https://github.com/user-attachments/files/16073380/donut_falls_summary.json)

**Comment by erinyoung** [comment]
Your summary file is the same as the tsv. 

So... it's unclear what is happening.

There's definitely a bug somewhere. I'd love for you to share your reads, so I can fix it.

**Comment by whottel** [comment]
Sounds good, you should be receiving a link shortly.

**Comment by RoyUnderwoodAbramski** [comment]
Can you remove me from this email list? I have clicked unsubscribe many times.

**Comment by erinyoung** [comment]
@RoyUnderwoodAbramski , my apologies, but it looks like you signed up for notifications from github for all activity of this repository. Only you can unsubscribe from these notifications. The github links sent to you should help you limit your notifications.

**Comment by erinyoung** [comment]
@whottel , it looks like it wasn't a bug, but a features that wasn't full tested.

`mash -c 20` is intended to subsample reads to 20X coverage to create the msh files, but it seems to increase mash distances too much.

I still need to do some testing, so a new release probably won't occur until next week.

My apologies.

**Comment by whottel** [comment]
No worries, thanks for looking into this!

**Comment by erinyoung** [comment]
My apologies for taking so long with this!

The mash dist issue should be resolved now!!!

I have removed the `-c` argument from mash dist and raised the threshold from mash dist to `0.05`. This should still filter out sample swaps (which is likely more a MY problem than anything else), but allow normal workflow usage.

**Comment by whottel** [comment]
Thanks, it looks to be working now.

**Comment by erinyoung** [comment]
Perfect!
